services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME:-taskdb}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-taskdb}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-network

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address :9001 /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-network

  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 user password;
      /usr/bin/mc mb minio/test-bucket;
      /usr/bin/mc anonymous set public minio/test-bucket;
      exit 0;
      "
    networks:
      - task-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-taskdb}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO:-validate}
      SERVICES_S3_ENDPOINT: http://minio:9000
      SERVICES_S3_ACCESS-KEY: user
      SERVICES_S3_SECRET-KEY: password
      SERVICES_S3_BUCKETNAME: testbucket
    networks:
      - task-network
    restart: on-failure

networks:
  task-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: